FROM public.ecr.aws/lambda/ruby:4.0

RUN dnf install -y gcc make && dnf clean all

COPY Gemfile Gemfile.lock ./
RUN bundle config set without "development test" && bundle install

COPY lib/ ${LAMBDA_TASK_ROOT}/lib/
COPY lambda/inbox_sync.rb ${LAMBDA_TASK_ROOT}/lambda_function.rb
COPY lambda/matrix_notifier.rb ${LAMBDA_TASK_ROOT}/matrix_notifier.rb

ENV RUBYLIB=${LAMBDA_TASK_ROOT}/lib
ARG BUILD_CONTENT_HASH=unknown
ENV BUILD_CONTENT_HASH=${BUILD_CONTENT_HASH}

CMD ["lambda_function.WeblogAuthoring::InboxSyncLambdaHandler.call"]
