FROM public.ecr.aws/lambda/nodejs:24 AS build

WORKDIR /build
COPY package.json package-lock.json tsconfig.bluesky-oauth.json ./
RUN npm ci
COPY lambda/bluesky_oauth/ lambda/bluesky_oauth/
RUN npm run build:bluesky-oauth

FROM public.ecr.aws/lambda/nodejs:24
COPY --from=build /build/node_modules ${LAMBDA_TASK_ROOT}/node_modules
COPY --from=build /build/dist/bluesky-oauth ${LAMBDA_TASK_ROOT}/
CMD ["handler.handler"]
