module WeblogAuthoring
  class DiaryNavigation
    DATE_ROUTE: Regexp
    @database: _PageRepository | DraftReader
    def initialize: (_PageRepository | DraftReader) -> void
    def neighbors: (String) -> Hash[String, String?]
  end
end
